config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users

  get "/login" => "session#new"
  post "/login" => "session#create"
  get "/logout" => "session#destroy"
  

  
  #Few ways to call only what you need without going crazy
  # get "/categories" => "categories#index"

  # get "/categories/:id" => "categories#show", as: :category
  # resources :categories, except: [:destroy, :update, :edit, :create, :new]
  # resources :categories, only: [:index, :show]
	# def self.resources(resource_name, options = {})

	# end 


	resources :categories, only: [:index, :show] do 
  	resources :articles, shallow: true
	end

  root 'welcome#index'


end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :category
	has_many :article_users
	has_many :users, through: :article_users

end

app/models/article_user.rb
class ArticleUser < ApplicationRecord
	belongs_to :user
	belongs_to :article 
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :articles
	

end

app/models/user.rb
class User < ApplicationRecord

	has_many :created_articles, class_name: "Article", foreign_key: "creator_id"
	has_many :article_users
	has_many :articles, through: :article_users

	validates :username, :password, presence: true
	validates :email, presence: true, uniqueness: true

	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	# before_action :all_articles, only: [:index, :create]
	# respond_to :html, :js

	def index
		@articles = Article.all
	end

	def new
		@category = Category.find(params[:category_id])
		@article = Article.new

		respond_to do |format|
	    format.html
	    format.js {}
  	end
	end

	def edit
  	@article = Article.find(params[:id])
	end

	def create
		@category = Category.find(params[:category_id])

		@article = @category.articles.create(article_params)
		if @article.save
			redirect_to category_path(@category)
		else
			render "new"
		end

	end

	def show
		@article = Article.find(params[:id])
	end


	def destroy
		@article = Article.find(params[:id])
  	@article.destroy
 
  	redirect_to categories_path

  	respond_to do |format|
	    format.html
	    format.json
  	end
	end

	def update
		@article = Article.find(params[:id])
 
	  if @article.update(article_params)
	    redirect_to article_path(@article)
	  else
	    render 'edit'
	  end
	end

	private
	  def article_params
	    params.require(:article).permit(:description, :conditon, :price, :category_id)
	  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@category = Category.all
	end

	def new
		@category = Category.new
	end

	def show
		@category = Category.find(params[:id])
		render html: "", status: :not_found unless @category
	end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
include SessionHelper

	def new
	end

	def create
		
		@user = User.find_by_email(params[:email])
			
			if @user && @user.authenticate(params[:password])
				login(@user)
				redirect_to user_path(@user)
			else
				redirect_to login_path
			end
	end

	def destroy
		logout
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	include SessionHelper


	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			login(@user)
			redirect_to user_path(@user)
		else
			flash[:error] = "An error occured"
			render "new"
		end

	end


	def show
		if params[:id].to_i == current_user.id
			@user = User.find(params[:id])
		else
			redirect_to user_path(@user)
		end
	end

private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation,:article)
  end




end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/session_helper.rb
module SessionHelper


	def login(user)
		session[:user_id] = user.id
	end

	def logout
		session.clear
	end

	def current_user
		if session[:user_id]
			User.find(session[:user_id])
		else
			nil
		end
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for  @article  do |f| %>
 
  <p>
    <%= f.label "Description" %><br>
    <%= f.text_field :description %>
  </p>
 
  <p>
    <%= f.label "Condition" %><br>
    <%= f.text_area :conditon %>
  </p>
 
  <p>
    <%= f.label "Price" %><br>
    <%= f.text_area :price %>
  </p>

  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/_new.html.erb
<%= form_for ([@category, @category.articles.build])  do |f| %>

  <p>
    <%= f.label "Description" %><br>
    <%= f.text_field :description %>
  </p>
 
  <p>
    <%= f.label "Condition" %><br>
    <%= f.text_field :conditon %>
  </p>

  <p>
    <%= f.label "Price" %><br>
    <%= f.text_field :price %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= render "form" %>
 
<%= link_to 'Back', article_path %>

app/views/articles/edit.js.erb
$("h1").hide()
$("p").hide()
$('#edit').hide().after('<%= j render ("form") %>');

app/views/articles/index.html.erb
<p>This are your articles</p>

app/views/articles/new.html.erb
<%= render "new" %>

app/views/articles/new.js.erb
$('#new_article').hide().after('<%= j render ("new") %>');
$("h1").hide()

app/views/articles/show.html.erb
<h1><%=@article.description%></h1>
<p><%=@article.conditon%></p>
<p>$<%=@article.price%></p>

<%= link_to 'Edit', edit_article_path(@article), remote: true, id: "edit" %>
<%= link_to 'Delete', @article, remote: true, method: :delete, class: "delete", data: {confirm:"Are you sure?"} %>

app/views/categories/index.html.erb
<p>Categories</p>

<table>
  <tr>
    <th><h1>Title</h1></th>
  </tr>
 
  <% @category.each do |category| %>
    <tr>
      <td> <h3><a href="/categories/<%=category.id%>"><%= category.title %></a></h3></td>
    </tr>
  <% end %>
</table>

app/views/categories/show.html.erb
<%= form_tag(category_path(@category), method: :get) do %>
  <%= text_field_tag :article, params[:article] ,id: "search_term"%>
  <%= submit_tag 'Search',name: nil %>
<% end %>

<p>All articles that belongs to <%=@category.title%> </p>


<ul>
	<% @category.articles.each do |article| %>
			<h1> <a href="/articles/<%=article.id%>"><%= article.description %></a></h1>
	<% end %>
</ul>




<%= link_to 'Create article', new_category_article_path(@category),id: "new_article",remote: true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Craiglist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  	<%= render "/header" %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/session/new.html.erb
<%= form_tag "/login" do  %>
  
  <p>
    <%= label :email, "Email" %><br>
    <%= text_field_tag :email %>
  </p>

  <p>
    <%= label :password, "Password" %><br>
    <%= password_field_tag :password %>
  </p>
 
  <p>
    <%= submit_tag "submit" %>
  </p>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <p>
    <%= f.label "Username" %><br>
    <%= f.text_field :username %>
  </p>
 
  <p>
    <%= f.label "Email" %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label "Password" %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field :password_confirmation %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.email%> </h1>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Thanks for using us</p>
<%= link_to 'Categories', categories_path %>